# Generated by Django 3.0.5 on 2020-05-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvorguesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, default='', to='anvorguesa.Ingrediente'),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
