# Generated by Django 3.0.5 on 2020-05-04 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anvorguesa', '0002_auto_20200502_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hamburguesa',
            old_name='img',
            new_name='imagen',
        ),
    ]
